# permissions for end users to edit networks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-editor-role
rules:
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks/status
  verbs:
  - get
