# permissions for end users to view networks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: network-viewer-role
rules:
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks/status
  verbs:
  - get
