---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks/finalizers
  verbs:
  - update
- apiGroups:
  - hcloud.sva.codes
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hcloud.sva.codes
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - hcloud.sva.codes
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hcloud.sva.codes
  resources:
  - volumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - volumes/finalizers
  verbs:
  - update
- apiGroups:
  - hcloud.sva.codes
  resources:
  - volumes/status
  verbs:
  - get
  - patch
  - update
