# permissions for end users to view sshkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshkey-viewer-role
rules:
- apiGroups:
  - hcloud.sva.codes
  resources:
  - sshkeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - sshkeys/status
  verbs:
  - get
