# permissions for end users to edit sshkeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sshkey-editor-role
rules:
- apiGroups:
  - hcloud.sva.codes
  resources:
  - sshkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.sva.codes
  resources:
  - sshkeys/status
  verbs:
  - get
